siteUid: null
sortOrder: 5
template: /calendar-demo/week
uriParts:
  - calendar-demo/week/
  -
    - year
    - '\d{4}'
  - /
  -
    - month
    - '(?:0?[1-9]|1[012])'
  - /
  -
    - day
    - '(?:0?[1-9]|[12][0-9]|3[01])'
uriPattern: 'calendar-demo/week/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>/<day:(?:0?[1-9]|[12][0-9]|3[01])>'
