field: be7373cf-5af8-4a9c-92bd-11ab39541795
fieldLayouts:
  4e3c7fbc-d76e-4650-8ad6-3a8d63fceddc:
    tabs:
      -
        elements:
          -
            fieldUid: 8c2efa0e-94d5-4d7d-86fc-b0af9e8d6f2c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 45e98e00-01d3-4272-aa08-0b1227d51b81
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f93ba9ca-aed6-465b-871c-a518711b649c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  45e98e00-01d3-4272-aa08-0b1227d51b81:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:c7803b14-f9ca-4ea2-8adb-77d4730289de'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Select Background Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:c7803b14-f9ca-4ea2-8adb-77d4730289de'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8c2efa0e-94d5-4d7d-86fc-b0af9e8d6f2c:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Heading.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f93ba9ca-aed6-465b-871c-a518711b649c:
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 7e56e437-1c93-46fe-8cdd-77c67ee0edf1
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_buttons}}'
      fieldLayout: matrix
      maxRows: '2'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add Button'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: block
name: 'Edit Header'
sortOrder: 1
