fieldLayouts:
  7a297c2c-2e13-4024-8c57-a4db0792fb7e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 843dd5e5-1e6b-49b2-b158-cfcf041098c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be7373cf-5af8-4a9c-92bd-11ab39541795 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f90a4c70-6bfe-463a-8c97-a592a275a9fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 995cc5a8-988f-47f0-ac78-76d6b68f6ac6 # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d83a112-74ad-48e3-810f-c5439557934f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3da8f1bb-df6c-4042-a213-c253a40d649d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6c184387-ba60-4935-8061-dd95b2f72809 # SEO
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53887737-eabb-492f-b3c7-4db251aceb38
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 17561247-0c65-4dd3-bfdd-0621d93f74ad
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 9d256421-0632-483e-ab16-fe4449e04977 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
