fieldLayouts:
  bd854859-fb1f-452f-b890-952339526424:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6e98616b-f275-44b8-850c-59d0bb424c74 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 145bc570-e681-4deb-934f-fc4840e12a77
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d379360d-3453-40b9-8c2d-65f2adf60b11
        userCondition: null
handle: legal
hasTitleField: false
name: Legal
section: 1a75673f-66e1-435d-a8f3-3e174804f7f2 # Legal
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
