fieldLayouts:
  26d1add7-adf3-4626-bc0f-d661f2b5e29b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6e98616b-f275-44b8-850c-59d0bb424c74 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cac6e292-7095-4c5c-a597-0dea22e4e116
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 498b9a9b-f019-4487-b4e0-9a743f1cc672
        userCondition: null
handle: mainMenu
hasTitleField: false
name: 'Main Menu'
section: d12aeb65-dd35-4b14-b50e-836d83eaee1c # Main Menu
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
