dateModified: 1592412700
email:
  fromEmail: cornelius@mostlyserious.io
  fromName: 'MS Craft'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  f440ccb2-63d7-4c7a-bb97-2b220919a425:
    name: Common
siteGroups:
  381df8ee-7145-4cf5-9db6-2d185f517753:
    name: 'MS Craft'
sites:
  06b4d470-302c-492f-a11a-b0062f294d1f:
    baseUrl: $PRIMARY_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: 'MS Craft'
    primary: true
    siteGroup: 381df8ee-7145-4cf5-9db6-2d185f517753
    sortOrder: 1
system:
  edition: solo
  live: true
  name: 'MS Craft'
  schemaVersion: 3.4.10
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
