baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: $PRIMARY_SITE_NAME
primary: true
siteGroup: 3dc3f5a1-bcf9-4805-9a54-f5dda1ad45a9 # $PRIMARY_SITE_NAME
sortOrder: 1
