childBlocks: null
description: null
field: be7373cf-5af8-4a9c-92bd-11ab39541795 # Header
fieldLayouts:
  99c8eddf-7322-4397-97f4-943783ccb2be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aca3b467-9b53-4288-91a9-eda4802a7623 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab85e266-b704-4a52-b08c-26c12eb1f0c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17eb1569-4de9-43de-9fc2-ae39a4845d60 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ce06d7a-633e-4aa4-81c8-99ed6b0a2256
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14bc7956-d13d-4317-8a7c-56b2bf6dca14 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88839b51-0e9b-4943-b05c-69eba9c81c64
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c36b2c0-2a98-4100-897b-4503119fb962
        userCondition: null
group: null
handle: block
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Edit Header'
sortOrder: 1
topLevel: true
