childBlocks: null
description: ''
enabled: true
field: 995cc5a8-988f-47f0-ac78-76d6b68f6ac6 # Blocks
group: null
handle: foobar
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Foobar
sortOrder: 3
topLevel: true
