childBlocks: null
conditions: null
description: null
enabled: true
field: 9a2e6d73-49cc-4aa9-89da-29c29cc4a000 # Code Blocks
fieldLayouts:
  d734c067-162e-42a5-9ad0-9151c679e681:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d6cfec69-0b38-4af7-9020-cdbbb89273ea # Code
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87cc4914-0593-42a4-b549-a7e14f8c99b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66c31629-070a-4dd5-967b-4622350fcc3b
        userCondition: null
group: fc1eb19e-c206-4b9a-adc3-32ed25f88eab # Head
groupChildBlockTypes: true
handle: headTop
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Head Top'
sortOrder: 2
topLevel: true
