contentColumnType: string
fieldGroup: abf8e78e-1b0c-422c-bbff-9c89770e9906
handle: blocks
instructions: ''
name: Blocks
searchable: true
settings:
  maxBlocks: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: true
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
