columnSuffix: null
contentColumnType: string
fieldGroup: 38b79782-e200-468f-9633-323021ffa8ca # Common
handle: button
instructions: null
name: Button
searchable: false
settings:
  allowCustomText: true
  allowTarget: true
  autoNoReferrer: true
  customTextMaxLength: 0
  customTextRequired: false
  defaultLinkName: entry
  defaultText: ''
  enableAllLinkTypes: false
  enableAriaLabel: true
  enableElementCache: false
  enableTitle: false
  typeSettings:
    asset:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: true
      sources: '*'
    category:
      allowCrossSiteLink: false
      allowCustomQuery: true
      enabled: true
      sources: '*'
    custom:
      allowAliases: false
      disableValidation: false
      enabled: false
    email:
      allowAliases: false
      disableValidation: false
      enabled: true
    entry:
      allowCrossSiteLink: false
      allowCustomQuery: true
      enabled: true
      sources: '*'
    site:
      enabled: false
      sites: '*'
    tel:
      allowAliases: false
      disableValidation: false
      enabled: true
    url:
      allowAliases: false
      disableValidation: true
      enabled: true
    user:
      allowCrossSiteLink: false
      allowCustomQuery: true
      enabled: false
      sources: '*'
translationKeyFormat: null
translationMethod: none
type: lenz\linkfield\fields\LinkField
