columnSuffix: null
contentColumnType: string
fieldGroup: abf8e78e-1b0c-422c-bbff-9c89770e9906 # Complex
handle: header
instructions: null
name: Header
searchable: true
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
