contentColumnType: string
fieldGroup: ec7644f6-7285-429f-9185-28284f2532a4
handle: menu
instructions: ''
name: Menu
searchable: false
settings:
  contentTable: '{{%matrixcontent_menu}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
