columnSuffix: cbtsycyn
contentColumnType: text
fieldGroup: 38b79782-e200-468f-9633-323021ffa8ca # Common
handle: seo
instructions: null
name: SEO
searchable: true
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoImage
    - robots
  generalTabEnabled: '1'
  sitemapEnabledFields:
    - sitemapUrls
  sitemapTabEnabled: '1'
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
