dateModified: 1600880938
email:
  fromEmail: cornelius@mostlyserious.io
  fromName: 'MS Craft'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  icon-picker:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  neo:
    edition: standard
    enabled: true
    schemaVersion: 2.8.0
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  usermanual:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
system:
  edition: solo
  live: true
  name: 'MS Craft'
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
