fieldLayouts:
  740d34d6-4e4b-4dcd-89f5-efe801ca4955:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9a2e6d73-49cc-4aa9-89da-29c29cc4a000 # Code Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a3279e9-e8e6-4c0a-81b7-6d42848ec5fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2eb767cf-7dd2-4506-94f5-4a74a76f80e5
        userCondition: null
handle: code
name: Code
sortOrder: 5
