fieldLayouts:
  9a2b1340-8d36-428c-b8c1-6a81ddb7bb07:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6e98616b-f275-44b8-850c-59d0bb424c74 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c34d0026-68d5-4a57-9fb9-49bc56005435
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6374103d-831d-477e-aa19-4e8e10dfa63f
        userCondition: null
handle: footer
name: Footer
sortOrder: 3
