fieldLayouts:
  a89e0548-b67d-4ad6-87cd-cba448f7a3cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6e98616b-f275-44b8-850c-59d0bb424c74 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cd56104-5324-402c-b77c-55aaf27143aa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52aab83b-ff8a-44e6-84c9-d43f8c7c7077
        userCondition: null
handle: legal
name: Legal
sortOrder: 4
